config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  match '/send_mail', to: 'welcome#send_mail', via: 'post'
  resources :posts

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  message    :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "d.r.carvalho89@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id                   :integer          not null, primary key
#  title                :string(255)
#  content              :text(65535)
#  field                :string(255)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  picture_file_name    :string(255)
#  picture_content_type :string(255)
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#

class Post < ActiveRecord::Base
	has_attached_file :picture, :styles => { :medium => "400x400>", :thumb => "100x100>" }
  	validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  http_basic_authenticate_with :name => "diana", :password => "3j1B12Nw5", :except => [:index, :show,:send_mail]
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params[:post].permit(:title,:field,:content,:picture,:description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	

	def send_mail
	    name = params[:name]
	    email = params[:email]
	    body = params[:message]
	    ContactMailer.contact_email(name, email, body).deliver
	    redirect_to '/#contacts', flash:{success: "Your message has been sent. I will get in touch as soon as possible.Thank you!"}
	end
end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
	title Diana Carvalho
	meta name="viewport" content="width=device-width, initial-scale=1"
	= stylesheet_link_tag 'application','http://fonts.googleapis.com/css?family=Raleway:400,800,700,600,500'
	= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Abel'
	=stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Muli'
	= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Josefin+Sans:400,600,700'
	= stylesheet_link_tag 'application', media: 'all'

    = favicon_link_tag 'favicon-32x32.png', rel:'icon',type:"image/png" 
    = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/foundation/5.1.1/js/foundation.min.js"
  	= javascript_include_tag "vendor/modernizr"
	= javascript_include_tag :application

	= csrf_meta_tags
   
   	nav class="top-bar" data-topbar=''
		ul class="title-area"
			li class="name"
				=link_to image_tag('logo.png'),'/'
				li.toggle-topbar.menu-icon
							a href="#"
								span 	
		section class="top-bar-section"
			
			ul class="right"

				li =link_to 'About','/#about'
				li =link_to 'Services' , '/#services'
				li =link_to 'Contacts','/#contacts'
				li =link_to 'Writing',posts_path
				li =link_to 'https://www.linkedin.com/profile/view?id=211553168', target: '_blank'
					i class="fa fa-linkedin"
    == yield

app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message
  =f.label :title
  =f.text_field :title
  =f.label :field
  =f.text_field :field
  =f.label :description
  =f.text_area :description, maxlength:'100'
  =f.label :content
  =f.text_area :content, :class => 'ckeditor'
  =f.file_field :picture
  = f.submit class:"tiny button btt-send"

app/views/posts/edit.html.slim
.row.post
	h1 Editing post

	== render 'form'

	= link_to 'Show', @post
	'|
	= link_to 'Back', posts_path

app/views/posts/index.html.slim
.row.post.transitions-enabled.infinite-scroll.clearfix id="masonry-container"
	- for post in @posts 
		
		.item.box.col2 
			.content
				h1.title = post.title
				p.description =post.description
				.view-link 
					=link_to 'view more >', post_path(post.id)
				br
				.field
					i class="fa fa-tags"  &nbsp;
					span =post.field 
				.date
					i class="fa fa-clock-o" &nbsp;
					span =post.created_at.strftime("%d %b %Y")

 		

app/views/posts/new.html.slim
.row.post
	h1 New post

	== render 'form'

	= link_to 'Back', posts_path

app/views/posts/show.html.slim
.row.post
	p#notice = notice
	div.large-10.columns.large-offset-1.showitem
		= image_tag @post.picture.url(:medium)
		h1.title =@post.title
		i class="fa fa-tags"  &nbsp;
		span =@post.field
		br
		.content
			=raw(@post.content)

		= link_to '< Back', posts_path

app/views/welcome/index.html.slim
.fullWidth id="dianaonrails"
	section id="homepage"
		
		.row
			.large-12.columns.top-text
				
				.main Hello, I'm Diana
				hr
				.sub UX Designer & Front-End developer
		.row		
			.large-8.large-offset-2.columns.sentence
				span I want to create 
				span.bold Useful, 
				br 
				span.bold Delightful 
				span and 
				span.bold Beautiful 
				span software.	
	section id="about"
		h1 KNOW MORE ABOUT ME
		hr
		.row.education
			h3.title My Story so far...
			.small-6.large-6.columns
				p I'm a 26 year old UX designer and front-end developer from Lisbon, Portugal. I graduated from the University of Lisbon in Computer Science, in 2012. 
				p While in college I started working in a startup company as a software developer. Since then, I have been working as a web developer in a bank and an IT company.
				p As time went by, I got in touch with UX and I started to study it. I didn't put aside coding and I am studing AngularJS also as part of the Front-End development. I want to join both UX design and coding, be part of a team and contribute.
				p I am now working as a freelancer, creating websites and putting my skills into action.

			.large-6.columns.img-face
				=image_tag('about-dianaux.png')		
		.row.about
			h3.title More about what I know
			.large-6.columns
				h2 Coding
				.large-8.large-offset-2.columns
					div id="donut-coding"
			.large-6.columns
				h2 UX design
				.large-8.large-offset-2.columns
					div id="donut-ux"

					 
	section id="services"
		h1 SERVICES
		hr		
		.row.whatido
			h3.title What can I do for you...
			.small-8.small-offset-2.large-3.large-offset-0.columns
				.icon-item
					.brainstorm
						=image_tag("brainstorm-icon.png")
					h4 Brainstorm 
					span.description
						'( Business Requirements )
			.small-8.small-offset-2.large-3.large-offset-0.columns		
				.icon-item
					.design
						=image_tag("prototyping-icon.png")
					h4 Prototyping / Design
					span.description
						'( Create guidelines and design )
			.small-8.small-offset-2.large-3.large-offset-0.columns
				.icon-item
					.usertest
						=image_tag("user-test-icon.png")
					h4 User testing 
					span.description 
						'( Make sure that users understand and can navigate intuitively )
			.small-8.small-offset-2.large-3.large-offset-0.columns.code-item
				.icon-item
					.code
						=image_tag("code-icon.png")
					h4 Code 
					span.description 
						'( Give life to your website )
	section id="contacts"
		h1 GET IN TOUCH
		hr
		.row
			.large-12.columns
				div.description
					h4 I’m always pleased to chat about work and meet new people in the industry. 
					h4 Send me a message using the form below.
				div.success-message
					=flash[:success]
				= form_tag(send_mail_path) do
					div.small-12.large-6.columns style="padding-left:0;"
	            		= label_tag 'name', 'Name *'
	                	= text_field_tag 'name', nil, class: 'form-control', placeholder: 'Your Name',required:true
	            	div.small-12.large-6.columns style="padding-left:0;padding-right:0;"
		                = label_tag 'email', 'Email *'
		                = email_field_tag 'email', nil, class: 'form-control', placeholder: 'Your Email Address',required:true
	            	div.large-12.columns style="padding-right:0; padding-left:0;"
		               	= label_tag 'message', 'Write me your message'
		               	= text_area_tag 'message', nil,rows: 8, placeholder: 'Message...'
	            		= submit_tag 'Send', class:"tiny button btt-send"
		        end   
			    //.large-2.columns
			    	//i class="fa fa-location-arrow fa-3x"    